### ISSUE TITLE
Results in error

### ISSUE THREAD

**Issue by inancgumus** [ctrlplusb/preact-compat-hmr#1]
_Do you have any idea why does it happen like this?_

``` javascript
Hash: 3ba238068779fdfc5094
Version: webpack 2.1.0-beta.19
Time: 544ms
  [12] multi main 40 bytes {0} [built]
    + 12 hidden modules

ERROR in ./src/index.js
Module build failed: Error: Cannot remove "babel-plugin-transform-es2015-modules-commonjs" from the plugin list.
    at Object.<anonymous> (/Users/inanc/preact-compat-hmr/node_modules/babel-preset-es2015-webpack/index.js:35:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /Users/inanc/preact-compat-hmr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:391:22
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/inanc/preact-compat-hmr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:387:20)
    at OptionManager.mergePresets (/Users/inanc/preact-compat-hmr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:10)
    at OptionManager.mergeOptions (/Users/inanc/preact-compat-hmr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:330:14)
    at OptionManager.addConfig (/Users/inanc/preact-compat-hmr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/Users/inanc/preact-compat-hmr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:436:16)
    at OptionManager.init (/Users/inanc/preact-compat-hmr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
    at File.initOptions (/Users/inanc/preact-compat-hmr/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/inanc/preact-compat-hmr/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/Users/inanc/preact-compat-hmr/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/inanc/preact-compat-hmr/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/inanc/preact-compat-hmr/node_modules/babel-loader/index.js:88:12)
 @ multi main
```

**Comment by ctrlplusb** [comment]
I am guessing, but maybe this is due to the upgrades to `babel-core` and `babel-preset-es2015`.  It is recommended not to use the `babel-preset-es2015-webpack`, but rather use `babel-preset-es2015` with the modules option disabled.  Could you try that?
- Replace `babel-preset-es2015-webpack` with `babel-preset-es2015` and then disable modules as per the [docs](https://babeljs.io/docs/plugins/preset-es2015/)

**Comment by ctrlplusb** [comment]
@deeperx Thanks for the report!

I had a try out of my theory and turns out I guessed right! :)  I've updated the codebase accordingly and all is ok again.

**Comment by inancgumus** [comment]
@ctrlplusb Thx for the commit man, np :) I'd worked on that 2 days ago and it was working with `babel-preset-es2015` and I forgot to make a push request to you.
